{{/*
SPDX-FileCopyrightText: (C) 2026 Intel Corporation
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mqtt.fullname" . }}-config
  labels:
    {{- include "mqtt.labels" . | nindent 4 }}
    app.kubernetes.io/component: mqtt
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
    persistence true
    persistence_location /mosquitto/data/
    log_dest file /mosquitto/log/mosquitto.log
