# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: mqtt
description: Eclipse Mosquitto MQTT broker subchart
type: application
version: 1.0.0
appVersion: "2.0"
