"""
Convert VLM page-level answer text files into rubric-like JSON artifacts.

Input:
    A folder containing page_*.txt files generated by generate_rubric_from_blank.py.

Output:
    - answer_key.json
    - Q*_auto.json

This is a heuristic converter. Generated outputs are marked with needs_review=true.
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any


QUESTION_HEADER_RE = re.compile(
    r"^\s*(?:[-*]\s*)?(?:\*\*)?\s*(?:题目\s*([0-9]+(?:\s*\([0-9]+\))?)|第\s*([0-9]+)\s*题)\s*[：:]\s*(?:\[([^\]\n]+)\])?",
    flags=re.MULTILINE,
)

PAGE_FILE_RE = re.compile(r"page_(\d+)_answer\.txt$")


@dataclass
class QuestionItem:
    question_label: str
    question_type_text: str
    answer_text: str
    score_text: str
    notes_text: str
    source_page: int
    question_text: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Convert VLM answers to rubric-like JSON files")
    parser.add_argument("--input", required=True, help="Path to vlm_answers directory")
    parser.add_argument("--output", default=None, help="Output directory")
    parser.add_argument("--exam-id", default="auto_generated_exam", help="Exam id for metadata")
    parser.add_argument("--exam-name", default="Auto Generated Exam", help="Exam name for metadata")
    return parser.parse_args()


def read_vlm_response(text: str) -> str:
    marker = "VLM RESPONSE:"
    idx = text.find(marker)
    if idx == -1:
        return text
    body = text[idx + len(marker) :]
    body = body.lstrip("\n")

    # Drop the first separator line if present.
    lines = body.splitlines()
    if lines and set(lines[0].strip()) <= {"-"}:
        lines = lines[1:]
    return "\n".join(lines).strip()


def parse_score_to_int(score_text: str) -> int:
    # Prefer upper bound when the text contains a range like "3-4分".
    m_range = re.search(r"(\d+)\s*[-~到]\s*(\d+)", score_text or "")
    if m_range:
        return int(m_range.group(2))

    nums = re.findall(r"\d+", score_text or "")
    if not nums:
        return 0
    return int(nums[0])


def normalize_question_label(label: str) -> str:
    label = re.sub(r"\s+", "", label)
    return label.replace("(", "_").replace(")", "")


def split_question_label(label: str) -> tuple[str, str]:
    base = re.match(r"^(\d+)", label or "")
    if not base:
        return "", ""
    base_q = base.group(1)
    sub = ""
    m_sub = re.search(r"\((\d+)\)", label or "")
    if m_sub:
        sub = m_sub.group(1)
    return base_q, sub


def infer_objective_kind(type_text: str, answer_text: str) -> str:
    text = f"{type_text} {answer_text}"
    if "选择" in text:
        return "choice"
    if "判断" in text:
        return "true_false"
    return "blank"


def infer_subjective_kind(type_text: str) -> str:
    text = type_text or ""
    if "作文" in text:
        return "writing"
    if "翻译" in text:
        return "translation"
    if "赏析" in text:
        return "analysis"
    if "简答" in text or "主观" in text:
        return "reading_comprehension"
    return "analysis"


def clean_extracted_text(value: str) -> str:
    if not value:
        return ""

    # Drop obvious trailing separators or chain-of-thought markers.
    value = re.split(r"\n\s*-{8,}\s*$", value, maxsplit=1)[0]
    value = re.split(r"\n\s*\*\*注[:：]\*\*", value, maxsplit=1)[0]
    value = value.replace("</think>", "")

    value = value.strip()
    value = value.lstrip("* ")
    if value.startswith("[") and value.endswith("]") and len(value) >= 2:
        value = value[1:-1].strip()
    if value in {"**", "*", "-"}:
        return ""
    return value.strip()


def infer_is_objective(type_text: str, answer_text: str, score_text: str) -> bool:
    t = type_text or ""
    a = answer_text or ""
    s = score_text or ""

    if any(k in t for k in ["主观", "简答", "翻译", "赏析", "作文", "分析"]):
        return False
    if any(k in t for k in ["选择", "填空", "判断", "客观"]):
        return True

    # Single-option answer like A/B/C/D is almost always objective.
    if re.fullmatch(r"\s*[ABCD]\s*[。.]?\s*", a):
        return True

    # Numbered slots likely objective-like structured blanks.
    if parse_numbered_answers(a):
        return True

    # If score is 0 and answer is explanatory prose, default to subjective.
    if parse_score_to_int(s) == 0 and len(a) > 30:
        return False

    return False


def parse_numbered_answers(answer_text: str) -> list[tuple[str, str]]:
    results: list[tuple[str, str]] = []
    for line in answer_text.splitlines():
        m = re.match(r"^\s*(?:[-*]\s*)?[（(]?([0-9]+)[）)]\s*[：:]?\s*(.+?)\s*$", line)
        if m:
            results.append((m.group(1), m.group(2).strip()))
    return results


def extract_value(block: str, key: str, next_keys: list[str]) -> str:
    pattern = rf"{key}\s*[：:]"
    m = re.search(pattern, block)
    if not m:
        return ""
    start = m.end()
    tail = block[start:]
    end = len(tail)
    for nk in next_keys:
        m2 = re.search(rf"\n\s*{nk}\s*[：:]", tail)
        if m2:
            end = min(end, m2.start())

    # Stop when the model starts a new markdown section or meta narration.
    for extra_stop in [r"\n\s*\*\*", r"\n\s*用户", r"\n\s*</think>", r"\n\s*---{3,}"]:
        m3 = re.search(extra_stop, tail)
        if m3:
            end = min(end, m3.start())

    m4 = re.search(r"\n\s*[-*]\s*\*\*", tail)
    if m4:
        end = min(end, m4.start())

    return clean_extracted_text(tail[:end].strip())


def extract_question_text_from_context(resp: str, question_label: str) -> str:
    # Try to find lines like: 题目11：... or **题目11：** ...
    pattern = rf"题目\s*{re.escape(question_label)}\s*[：:]\s*(.+)"
    m = re.search(pattern, resp)
    if m:
        tail = m.group(1).strip()
        if tail and "类型" not in tail and "答案" not in tail:
            tail = clean_extracted_text(tail)
            if tail and tail not in {"**", "*", "-"}:
                return tail

    base_q, _ = split_question_label(question_label)
    if base_q:
        # Match quoted original question text such as: “10. ...”
        m2 = re.search(rf"[“\"]\s*{re.escape(base_q)}\s*[.．、]\s*([^”\"\n]+)", resp)
        if m2:
            return f"{base_q}. {clean_extracted_text(m2.group(1))}"

        # Match plain line style: 10. ...
        m3 = re.search(rf"(^|\n)\s*{re.escape(base_q)}\s*[.．、]\s*(.+)", resp)
        if m3:
            qline = clean_extracted_text(m3.group(2))
            if qline and "答案" not in qline and "分值" not in qline:
                return f"{base_q}. {qline}"
    return ""


def objective_quality_score(type_text: str, answer_text: str, question_label: str) -> int:
    score = 0
    text = f"{type_text} {answer_text}"
    if any(k in text for k in ["选择", "填空", "客观"]):
        score += 3
    if re.fullmatch(r"\s*[ABCD]\s*[。.]?\s*", answer_text or ""):
        score += 3
    if parse_numbered_answers(answer_text):
        score += 2
    if re.search(r"\(\d+\)", question_label or ""):
        score += 1
    if len(answer_text or "") > 180:
        score -= 3
    if any(k in (answer_text or "") for k in ["用户希望", "让我们", "图片中", "通常", "修正", "最终决定"]):
        score -= 4
    return score


def subjective_quality_score(type_text: str, answer_text: str) -> int:
    score = 0
    if any(k in (type_text or "") for k in ["主观", "简答", "翻译", "赏析", "分析", "作文"]):
        score += 3
    if len(answer_text or "") > 25:
        score += 1
    if re.fullmatch(r"\s*[ABCD]\s*[。.]?\s*", answer_text or ""):
        score -= 4
    return score


def parse_questions_from_response(resp: str, page_num: int) -> list[QuestionItem]:
    matches = list(QUESTION_HEADER_RE.finditer(resp))
    if not matches:
        return []

    items: list[QuestionItem] = []
    for i, m in enumerate(matches):
        start = m.start()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(resp)
        block = resp[start:end]

        label_from_topic = m.group(1) or m.group(2) or ""
        question_label = re.sub(r"\s+", "", label_from_topic)
        q_type = (m.group(3) or "").strip()
        if not q_type:
            q_type = extract_value(block, "类型", ["答案", "分值", "备注", "题目", "第"])
        answer_text = extract_value(block, "答案", ["分值", "备注", "题目"]) 
        score_text = extract_value(block, "分值", ["备注", "题目"]) 
        notes_text = extract_value(block, "备注", ["题目"]) 
        question_text = extract_question_text_from_context(resp, question_label)

        if not answer_text and not score_text and not notes_text:
            continue

        items.append(
            QuestionItem(
                question_label=question_label,
                question_type_text=q_type,
                answer_text=answer_text,
                score_text=score_text,
                notes_text=notes_text,
                source_page=page_num,
                question_text=question_text,
            )
        )

    return items


def parse_page_file(path: Path) -> list[QuestionItem]:
    content = path.read_text(encoding="utf-8", errors="ignore")
    response = read_vlm_response(content)

    m = PAGE_FILE_RE.search(path.name)
    page_num = int(m.group(1)) if m else 0
    return parse_questions_from_response(response, page_num)


def build_outputs(
    items: list[QuestionItem],
    exam_id: str,
    exam_name: str,
) -> tuple[dict[str, Any], dict[str, dict[str, Any]]]:
    objective_questions: dict[str, Any] = {}
    subjective_questions: dict[str, Any] = {}
    rubric_files: dict[str, dict[str, Any]] = {}

    all_pages = sorted({it.source_page for it in items})

    for it in items:
        qnum, sub_idx = split_question_label(it.question_label)
        if not qnum:
            continue
        qlabel_norm = normalize_question_label(it.question_label)
        score_value = parse_score_to_int(it.score_text)

        type_text = clean_extracted_text((it.question_type_text or "").strip())
        answer_text = clean_extracted_text((it.answer_text or "").strip())
        notes_text = clean_extracted_text((it.notes_text or "").strip())

        is_objective = infer_is_objective(type_text, answer_text, it.score_text)

        # Drop clearly noisy extracted segments before building artifacts.
        if not answer_text:
            continue

        if is_objective:
            numbered_answers = parse_numbered_answers(answer_text)
            # If question label itself is a sub-question (e.g. 1(3)), force group output.
            if sub_idx and not numbered_answers:
                numbered_answers = [(sub_idx, answer_text)]

            if numbered_answers:
                existing = objective_questions.get(qnum, {}) if isinstance(objective_questions.get(qnum), dict) else {}
                sub_questions: dict[str, Any] = dict(existing.get("sub_questions", {}))
                per_slot = score_value // len(numbered_answers) if score_value > 0 else 0
                for idx, ans in numbered_answers:
                    sub_questions[f"({idx})"] = {
                        "type": infer_objective_kind(type_text, ans),
                        "score": per_slot,
                        "format": "string",
                        "match_mode": "any",
                        "answer": [ans],
                    }
                objective_questions[qnum] = {
                    "type": "group",
                    "score": max(score_value, int(existing.get("score", 0) or 0)),
                    "sub_questions": sub_questions,
                    "needs_review": True,
                    "source_page": it.source_page,
                    "source_question_label": it.question_label,
                }
            else:
                answers = [
                    ln.strip(" -*")
                    for ln in answer_text.splitlines()
                    if ln.strip()
                    and not ln.strip().startswith("**")
                    and not ln.strip().startswith("用户")
                    and not ln.strip().startswith("让我们")
                ]
                if not answers and answer_text:
                    answers = [answer_text]

                # Keep objective answers concise; avoid carrying long narrative blocks.
                answers = [a for a in answers if len(a) <= 120]
                if not answers:
                    compact = answer_text.strip()
                    if len(compact) <= 120:
                        answers = [compact]
                    else:
                        continue

                objective_questions[qnum] = {
                    "type": infer_objective_kind(type_text, answer_text),
                    "score": score_value,
                    "format": "string",
                    "match_mode": "any",
                    "answer": answers,
                    "needs_review": True,
                    "source_page": it.source_page,
                    "source_question_label": it.question_label,
                }
        else:
            rubric_name = f"question{qnum}.json"
            subjective_questions[qnum] = {
                "alias": f"Q{qlabel_norm}",
                "type": infer_subjective_kind(type_text),
                "score": score_value,
                "rubric": rubric_name,
                "needs_review": True,
                "source_page": it.source_page,
                "source_question_label": it.question_label,
            }

            rubric_files[rubric_name] = {
                "question_id": f"Q{qlabel_norm}",
                "section": "auto_generated",
                "type": infer_subjective_kind(type_text),
                "total_score": score_value,
                "question_text": it.question_text,
                "context": {
                    "source_page": it.source_page,
                    "source_question_label": it.question_label,
                },
                "standard_answer_summary": answer_text,
                "scoring_points": [
                    {
                        "id": "p1",
                        "score": score_value,
                        "description": "Auto extracted scoring point",
                        "criteria": notes_text,
                        "hit_signals": [],
                    }
                ],
                "few_shot_examples": [],
                "notes": {
                    "auto_generated": True,
                    "needs_review": True,
                    "source_score_text": it.score_text,
                },
            }

    # Resolve qnum conflicts: if a question appears in both objective and subjective,
    # keep the side with higher confidence.
    overlap = set(objective_questions.keys()) & set(subjective_questions.keys())
    for q in overlap:
        obj = objective_questions[q]
        sub = subjective_questions[q]

        obj_score = objective_quality_score(
            str(obj.get("type", "")),
            "\n".join(obj.get("answer", [])) if isinstance(obj.get("answer"), list) else "",
            str(obj.get("source_question_label", "")),
        )

        sub_file = sub.get("rubric")
        sub_answer = ""
        if isinstance(sub_file, str) and sub_file in rubric_files:
            sub_answer = str(rubric_files[sub_file].get("standard_answer_summary", ""))
        sub_score = subjective_quality_score(str(sub.get("type", "")), sub_answer)

        if obj_score >= sub_score:
            # Keep objective, remove subjective rubric file.
            if isinstance(sub_file, str):
                rubric_files.pop(sub_file, None)
            subjective_questions.pop(q, None)
        else:
            objective_questions.pop(q, None)

    answer_key = {
        "metadata": {
            "description": "Auto-generated answer key converted from VLM outputs",
            "version": "0.1",
            "exam_id": exam_id,
            "exam_name": exam_name,
            "generated_at": datetime.now().isoformat(),
            "needs_review": True,
        },
        "objective_questions": objective_questions,
        "subjective_questions": subjective_questions,
    }

    return answer_key, rubric_files


def write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def main() -> int:
    args = parse_args()
    input_dir = Path(args.input)
    if not input_dir.exists() or not input_dir.is_dir():
        print(f"ERROR: input directory not found: {input_dir}")
        return 1

    output_dir = Path(args.output) if args.output else input_dir.parent / "rubric_like_output"
    output_dir.mkdir(parents=True, exist_ok=True)

    page_files = sorted(input_dir.glob("page_*_answer.txt"))
    if not page_files:
        print(f"ERROR: no page_*_answer.txt files found in: {input_dir}")
        return 1

    all_items: list[QuestionItem] = []
    for page_file in page_files:
        all_items.extend(parse_page_file(page_file))

    if not all_items:
        print("ERROR: no question blocks extracted. Check VLM output format.")
        return 1

    answer_key, rubric_files = build_outputs(
        all_items,
        exam_id=args.exam_id,
        exam_name=args.exam_name,
    )

    write_json(output_dir / "answer_key.json", answer_key)

    for file_name, rubric_data in rubric_files.items():
        write_json(output_dir / file_name, rubric_data)

    print("=" * 80)
    print("VLM answers converted to rubric-like files")
    print("=" * 80)
    print(f"Input : {input_dir}")
    print(f"Output: {output_dir}")
    print(f"Page files processed: {len(page_files)}")
    print(f"Question blocks extracted: {len(all_items)}")
    print(f"Objective questions: {len(answer_key['objective_questions'])}")
    print(f"Subjective questions: {len(answer_key['subjective_questions'])}")
    print("Generated files:")
    print("  - answer_key.json")
    print("  - question*.json (subjective rubrics)")
    print("NOTE: All outputs are first-pass and require manual review.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
