{{/*
SPDX-FileCopyrightText: (C) 2026 Intel Corporation
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.huggingfaceToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ovms.hfTokenSecretName" . }}
  labels:
    {{- include "ovms.labels" . | nindent 4 }}
    app.kubernetes.io/component: ovms
type: Opaque
data:
  token: {{ .Values.huggingfaceToken | b64enc | quote }}
{{- end }}
