# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
{{- if .Values.global.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-live-video-alert-agent-sa
  labels:
    {{- include "lva.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-ovms-sa
  labels:
    {{- include "lva.labels" . | nindent 4 }}
    app.kubernetes.io/component: inference
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-ovms-llm-sa
  labels:
    {{- include "lva.labels" . | nindent 4 }}
    app.kubernetes.io/component: inference
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-mqtt-sa
  labels:
    {{- include "lva.labels" . | nindent 4 }}
    app.kubernetes.io/component: mqtt
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-alert-agent-service-sa
  labels:
    {{- include "lva.labels" . | nindent 4 }}
    app.kubernetes.io/component: alert-agent-service
automountServiceAccountToken: false
{{- end }}
